### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by jcaillon** [jcaillon/3P#1]
# Personal to do list #

**Here lies the ideas i can have for enhancing the soft, i also use this list to log the bugs i find during my tests.
Pardon my french for what follows**

- [ ] set env, hide delete if there is nothing to del
- [ ] permettre la maj de 3P via le dossier partagé
- [ ] add CURRENT ENV dans le file explorer form
- [ ] dans menu switch environnement
- [ ] ajouter une boussole au refresh du file explorer + faire un refresh auto quand on change d'env...
- [ ] refaire les drops list en utilisant le yamui menu...
- [ ] mettre à jour le tree list quand on l'affiche pour la première fois
- [ ] yamuinotif, ajouter une scrollbar
- [ ] autocase quand on rentre un {.i}
- [ ] pour le compilation path... faire la règle suivante : soit c'est un chemin absolu et on MOVE seulement. soit c'est un ftp://user:password@host:port/path et dans ce cas on ENVOI FTP seulement, et sinon les deux
- [ ] Ajouter la version du Framework
- [ ] myVar ++ to myVar = myVar +
- [ ] Type double slash ('//') anywhere in a line (even in a middle of a word) and it will be commented
out or uncommented, then the cursor moves to the next line so it can be processed it the same way. If double slash is type at the end of a line, then a new empty comment is inserted at the end of the line and the cursor stays there

*****

- [ ] Snippets : $1 et $2.. pour les tabs stops; ${1:label}, tout les ${x:) sont liés et on s'arrête juste sur le premier, "label" est affiché par défaut et est sélectionné quand on fait tab. Si on fait entrée, sélectionne le dernier dollar.
- [x] QOL : add a warning / info on push/fetch buttons
- [x] Limit the number of popup for an update to one! since it's everyhour there were xxx displayed
- [x] in set environnement, left click open in npp, right click open in folder
- [x] replace buttonpressed by on click in shortcuts
- [x] Ajouter un -ct 2 après toutes les connexions aux bases
- [ ] Set > Super procedures, config identique à compilation path : appli \t suffix \t path, le path peut être soit relatif (par rapport au source path) soit absolu et permet de charger cette liste de fichier en persistent
- [ ] preview tags in SetInfoPage
- [ ] fermer popup de proposition de fichier CTRL+B
- [x] griser DELETE quand on modifie un env
- [x] replace NPPM_GETNPPVERSION
- [ ] dans Parser.Lexer.Tokenize() out of memory
- [x] changer le screenshot de presentation du menu
- [ ] /* --- Modif #30
- [ ] a chaque fois qu'on ajoute des lignes, on retient les numéros et on les corrige quand le parser est mis à jour
- [ ] add a command to update a function's prototype
- [ ] Ajout d'une procédure/function
- [ ] Ajouter les raccourcis de la sopratool
- [ ] Ajouter un autre type à progressExecution
- [ ] ALT+F2 to rename a variable
- [ ] Auto reindent : bien utiliser le boolean de code bien formaté avant de réindenter + faire une method IndentCode(int startLine, int endLine). à chaque fois qu'on ajoute une ligne on sauve la ligne modifié, quand on parse, si bool = true on reindente tt le block owner de la ligne à reindente
- [ ] créer le dossier de compil si il existe pas!!
- [ ] CTRL+Shift+N : nouveau fichier .p crée dans le %temp%
- [ ] CTRL+T : trace, ajouter aussi un snippet traces
- [ ] dans les tooltips, ajouter un lien vers chaque utilisation de la function/procedure qu'on pointe (easy avec les infos du code explorer)
- [ ] Ecran des compilation path : s'applique pour APPLI / END / FROMPATH/ TO PATH
- [ ] Extract Database : faire le bouton delete et le bouton view content (afficher la database sous forme de message box)
- [ ] faire le smart indent lorsqu'on finis d'écrire un end
- [ ] Faire un écran où on propose de rentrer deux liste de programmes, une liste côté client, une liste côté serveur -> ces programmes sont considérés comme étant chargés en persistent pour la session progress et leur func/proc accessibles par tout les autres progs
- [ ] Faire une fonction : start an appbuilder
- [ ] FileExplorer : mettre en top de liste les fichiers qui sont lister comme étant dans le même workpackage que le fichier courant?
- [ ] Finir les snippets!!
- [ ] finir les tags de modif
- [ ] gérer le clic droit sur le code explorer, mettre la possibilité d'aller jusqu'à la proc/le .i
- [ ] improve go to function, should find relative path adecomm/derp.i and not only search for derp.i
- [ ] Les fichiers commencant par _ ne generent pas correctement la .lst
- [ ] main appl > Tools > Compile everything, step 1 : refresh base local path folder list, step 2: 2 ovl, 1 to list all the folders, the second contains the folder to compile (on propose aussi un bouton select all), step 3 : launch compile process on selectd folders
- [ ] Mettre en place les options pour régler le proxy
- [ ] mettre l'affichage des espaces en option
- [ ] Ne pas copier le .ini dans le repertoire tempo!
- [ ] On peut ajouter la liste des .i, et des .p à appeler dans la completion list
- [ ] pour la compil/check syntax, on a besoin uniquement du propath pour avoir les includes, il en faut pas copier le .ini et ajouter dans le {&propath} uniquement les dossiers qui contiennent les trucs qu'on include, ça ira bien plus vite
- [ ] pour le CTRL + T, insérer : {custom_log.i "mon truc à logger"}
- [ ] Pour les fichiers de conf (hormis config) snippets, keyword, abbrev etc... boolean dans la config ->local true/false, si false on garde tout dans la dll on exporte rien, si true on previent l'user qu'il aurait pas les maj des fichiers et qu'il gardera les siens
- [ ] pour les snippets, rajouter des (%) pour remplacer des expression (par exemple pour dvi faire def var (%context_global_local)i_
- [ ] Prévoir un bouton "ping" de la database
- [ ] prévoir une fonction pour cacher tous les statements de l'appbuilder
- [ ] Proposer à l'utilisateur de mettre ses propres fonctions progress en raccourci {icon, nom, shortcut, program.p} faire un fichier d'interface avec divers info qu'il peut utiliser pour piloter son .p et lire un fichier de retour qu'il peut utiliser pour commander npp
- [ ] Proposer en option de définir un path commun pour les configurations, et sur le clic d'un bouton on remplace les fichiers de conf local par ceux du répertoire commun!!!!!!
- [ ] Rajouter des tooltips sur le code explorer, à l'identique des tooltips keywords
- [ ] real syntax highlighting
- [ ] remplacer le HACK pour cacher l'auto comp par un start record macro?
- [ ] Scrollbar doit descendre quand on clic dans un endroit sans le thumb
- [ ] si from appbuilder, dans l'update select, checker ou est le caret, si il est dans une zone normalement non éditable prévenir l'user qu'il fait de la merde
- [ ] si le plugin n'est pas chargé correctement, il faut squizzer le cleanup et le create menu !!! pour que l'import du plugin se passe sans encombres!!!
- [ ] tooltips : pour les types et les flags, rajouter des annotations pour gagner en compréhension
- [ ] tooltips code explorer...

#### Auto-completion

- [ ] Remplacer l'autocompletion par défaut de Npp, lire les fichiers /plugins/APIs et mimiquer le fonctionnement actuel décrit ici : http://docs.notepad-plus-plus.org/index.php/Auto_Completion
- [ ] Pour l'autocomp, faire un GetChild() dans l'autocompletionData et faire un truc plus générique qui fait qu'on AutocompletionData peut avoir des enfants qui seront affichés soit après un `.` (pour les tables par ex) ou après un `:` pour les handles
- [ ] Améliorer l'autocomplétion : changer le contexte pour après un `RUN ` il faut afficher des procédures à run
- [ ] Améliorer l'autocomp : changer le contexte pour `{ }` il faut afficher des fichiers à include
- [ ] auto comp: contexte `dynamic-function("` il faut proposer toutes les fonctions locales + les fonctions chargées en dynamique, qu'on a renseigné au préalable.
- [ ] remplacer l'autocomplete et la function list par defaut..
- [ ] ajouter le parse des publish/subscribe et mettre ça dans le code explorer

**Comment by jcaillon** [comment]
![image](https://cloud.githubusercontent.com/assets/11553075/11215506/d8ddb718-8d46-11e5-9bd3-db8cd9e9ec54.png)
![image](https://cloud.githubusercontent.com/assets/11553075/11215274/a84d092e-8d45-11e5-87c6-830d40460e14.png)
![image](https://cloud.githubusercontent.com/assets/11553075/11215041/8e342adc-8d44-11e5-9c3e-fef920076f46.png)

**Comment by jcaillon** [comment]
3P remplace les tabs par des espaces pour respecter l'indentation dans l'appbuilder, qui ne sait pas gérer les espaces

**Comment by jcaillon** [comment]
Lors d'une release : 
Bien penser à changer la version de la librairie et faire en sorte qu'elle soit identique au tag_name de la release qu'on va créer dans github

**Comment by jcaillon** [comment]
Me too

**Comment by jcaillon** [comment]
Post a comment on github <3

```Csharp
HttpWebRequest req = WebRequest.Create(new Uri(@"https://api.github.com/repos/jcaillon/3p/issues/1/comments")) as HttpWebRequest;
req.Method = "POST";
//req.ContentType = "application/json";
req.UserAgent = "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.2; .NET CLR 1.0.3705;)";

String username = "";
String password = "";
String encoded = System.Convert.ToBase64String(System.Text.Encoding.GetEncoding("ISO-8859-1").GetBytes(username + ":" + password));
req.Headers.Add("Authorization", "Basic " + encoded);
      
// req.Headers.Add("Authorization","Basic " + Convert.ToBase64String(new ASCIIEncoding().GetBytes(username +":"+password)));

StreamWriter writer = new StreamWriter(req.GetRequestStream());
writer.Write("{\"body\": \"Me too\"}");
writer.Close();

string result = null;
using (HttpWebResponse resp = req.GetResponse() as HttpWebResponse)  {
  StreamReader reader = new StreamReader(resp.GetResponseStream());
  result = reader.ReadToEnd();
}
WriteLine(result);

```

**Comment by jcaillon** [comment]
Pour la démo : 
- Les configs appliquées pour les fichiers progress :
  * espaces au lieu des tabs
  * bloquer l'autocomp par défaut
- Utiliser un prog serveur : D:\cnaf\SVN\boi-b-dev\src\serveur\bs00interv.p
  * Parcourir les catégories de l'autocomp
  * clic droit/gauche des catégories + ALT < >
  * buffer, temp tables
  * includes
  * run persistent
  * expliquer le filtrage + tri
  * Affichage des variables locales dans une proc
  * changement de contexte après ":"
- Tooltips
  * multiples déf pour un word (ex: available)
  * table link sur les triggers BOI_APPL
- CTR + B
- les thèmes
- montrer les fichiers de conf
- expliquer la configuration globale sur le rs28
-

**Comment by ccleaud** [comment]
Hey!
Looks you speek french.
"Super génial ce plugin, u grand merci pour le travail fourni"

**Comment by 3pUser** [comment]
### Julien (JULIEN-PCFIXE) ###
#### 3P version : v1.6.3, Notepad++ version : v6.9.2 ####
Last bug report this way?

**Comment by 3pUser** [comment]
### Julien (JULIEN-PCFIXE) ###
#### 3P version : v1.6.3, Notepad++ version : v6.9.2 ####
Last bug report this way?
